# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Rust.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

# Optional: Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
# services:
#   - mysql:latest
#   - redis:latest
#   - postgres:latest


stages:          # List of stages for jobs, and their order of execution
  - build

.rust_template: &rust_template
  stage: build
  image: "rust:slim"
  cache:
    key: shared-cache
    paths:
      - target/
  before_script:
    - rustup --version
    - rustc --version
    - cargo --version
    - rustup toolchain install stable
    - rustup toolchain install beta
    - rustup toolchain install nightly
    - rustup target add thumbv6m-none-eabi --toolchain stable
    - rustup target add thumbv6m-none-eabi --toolchain beta
    - rustup target add thumbv6m-none-eabi --toolchain nightly
    - rustup component add rustfmt
    - rustup component add clippy
    - cargo install flip-link

checks:
  <<: *rust_template
  script:
    - cargo fmt -p firmware --verbose -- --check    
    - cargo clippy -p firmware --verbose -- --check    

build-stable-release:
  <<: *rust_template
  script:
    - cargo build --release --target=thumbv6m-none-eabi

build-stable-dev:
  <<: *rust_template
  script:
    - cargo build --target=thumbv6m-none-eabi

build-beta-release:
  <<: *rust_template
  script:
    - cargo +beta build --release --target=thumbv6m-none-eabi

build-beta-dev:
  <<: *rust_template
  script:
    - cargo +beta build --target=thumbv6m-none-eabi

build-nightly-release:
  <<: *rust_template
  script:
    - cargo +nightly build --release --target=thumbv6m-none-eabi

build-nightly-dev:
  <<: *rust_template
  script:
    - cargo +nightly build --target=thumbv6m-none-eabi

