[package]
authors = ["Alexis Marquet <alexis@alexismarquet.com>"]
name = "firmware"
edition = "2018"
version = "0.3.0"


[dependencies]
cortex-m = "0.7.3"
cortex-m-rt = "0.7.0"
defmt = "0.3.0"
defmt-rtt = "0.3.0"
panic-probe = { version = "0.3.0", features = ["print-defmt"] }
stm32l0xx-hal = { path= "../stm32l0xx-hal", features = ["mcu-STM32L052K6Ux", "rt"]}
#stm32l0xx-hal = {version = "0.9.0", features = ["mcu-STM32L052K6Ux", "rt"]}
accelerometer = "~0.12"
lis3dh = {path = "../lis3dh-rs"}


[features]
no-sleep = []
default = []



[dev-dependencies]
defmt-test = "0.3.0"
